# Utiliser une image de base officielle de Node.js
FROM node:18-alpine

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier package.json et package-lock.json dans le répertoire de travail
COPY package*.json ./

# Installer les dépendances de l'application
RUN npm install

# Copier le reste des fichiers de l'application dans le répertoire de travail
COPY . .

# Construire l'application Angular
RUN npm run build


# Utiliser NGINX pour servir les fichiers statiques
FROM nginx:stable-alpine
# Copier la build dans le répertoire /usr/share/nginx/html
COPY --from=0 /app/.next/ /usr/share/nginx/html

#prend mon nginx.conf et écrase celui par défaut
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Exposer le port sur lequel l'application va s'exécuter
EXPOSE 80
# Démarrer l'application
CMD ["nginx", "-g", "daemon off;"]